window.BUILTIN_WORDS = [
  ["abandon", "/əˈbændən/", "放弃；抛弃", "Never abandon your plan after one bad day.", "a + bandon：把一件事扔到一边。"],
  ["ability", "/əˈbɪləti/", "能力；才能", "Reading builds your language ability.", "able 是能，ability 是能力。"],
  ["absence", "/ˈæbsəns/", "缺席；不存在", "His absence made the team worried.", "absent 的名词形式。"],
  ["absolute", "/ˈæbsəluːt/", "绝对的；完全的", "There is no absolute answer.", "absolutely 常见于口语：完全地。"],
  ["absorb", "/əbˈzɔːrb/", "吸收；理解", "Plants absorb water from the soil.", "像海绵吸收水，也可吸收知识。"],
  ["academic", "/ˌækəˈdemɪk/", "学术的；学院的", "Academic writing requires clear logic.", "academy 学院，academic 学术的。"],
  ["access", "/ˈækses/", "入口；使用权；访问", "Students need access to good books.", "有 access 才能进入或使用。"],
  ["accident", "/ˈæksɪdənt/", "事故；意外", "The accident happened on a rainy night.", "by accident 表示偶然地。"],
  ["accompany", "/əˈkʌmpəni/", "陪伴；伴随", "Music accompanied her study time.", "company 有陪伴的意思。"],
  ["achieve", "/əˈtʃiːv/", "实现；取得", "Small steps help you achieve big goals.", "achievement 是成就。"],
  ["acquire", "/əˈkwaɪər/", "获得；学到", "You acquire vocabulary through review.", "acquire knowledge 获得知识。"],
  ["adapt", "/əˈdæpt/", "适应；改编", "You must adapt to a new environment.", "adapt to 固定搭配：适应。"],
  ["adequate", "/ˈædɪkwət/", "足够的；合格的", "Adequate sleep improves memory.", "够用但不一定很多。"],
  ["adjust", "/əˈdʒʌst/", "调整；适应", "Adjust your plan when necessary.", "just 像校准，adjust 是调准。"],
  ["admire", "/ədˈmaɪər/", "钦佩；欣赏", "I admire her courage.", "admiration 是钦佩。"],
  ["admit", "/ədˈmɪt/", "承认；准许进入", "He admitted his mistake.", "admit doing sth. 承认做过某事。"],
  ["advance", "/ədˈvæns/", "前进；进步；提前", "Technology advances quickly.", "in advance 提前。"],
  ["advantage", "/ədˈvæntɪdʒ/", "优势；有利条件", "Practice gives you an advantage.", "take advantage of 利用。"],
  ["advertise", "/ˈædvərtaɪz/", "做广告；宣传", "The company advertised the new course.", "advertisement 是广告。"],
  ["affect", "/əˈfekt/", "影响", "Stress can affect your memory.", "常作动词，effect 常作名词。"],
  ["afford", "/əˈfɔːrd/", "买得起；承担得起", "I cannot afford to waste time.", "afford to do 承担得起做某事。"],
  ["agency", "/ˈeɪdʒənsi/", "机构；代理处", "The agency offers language courses.", "agent 代理人，agency 机构。"],
  ["aggressive", "/əˈɡresɪv/", "有进取心的；侵略性的", "An aggressive plan needs strong action.", "语境决定褒贬。"],
  ["allocate", "/ˈæləkeɪt/", "分配；拨出", "Allocate twenty minutes to review.", "locate 是定位，allocate 是分配位置。"],
  ["alter", "/ˈɔːltər/", "改变；修改", "You can alter your learning method.", "alter = change，但更正式。"],
  ["ambition", "/æmˈbɪʃn/", "雄心；抱负", "Her ambition is to enter university.", "ambitious 有抱负的。"],
  ["analyze", "/ˈænəlaɪz/", "分析", "Analyze your mistakes after practice.", "analysis 是名词：分析。"],
  ["annual", "/ˈænjuəl/", "每年的；年度的", "The annual exam is important.", "ann- 和 year 有关。"],
  ["anxiety", "/æŋˈzaɪəti/", "焦虑；担心", "Deep breathing can reduce anxiety.", "anxious 是焦虑的。"],
  ["apparent", "/əˈpærənt/", "明显的；表面上的", "It became apparent that he was tired.", "apparently 表示显然。"],
  ["appeal", "/əˈpiːl/", "吸引；呼吁；上诉", "The idea appeals to many students.", "appeal to 吸引。"],
  ["appetite", "/ˈæpɪtaɪt/", "食欲；欲望", "Exercise improves appetite.", "也可说 appetite for knowledge。"],
  ["apply", "/əˈplaɪ/", "申请；应用", "Apply this method to new words.", "apply for 申请；apply to 应用于。"],
  ["approach", "/əˈproʊtʃ/", "方法；接近", "A good approach saves time.", "既是名词方法，也是动词接近。"],
  ["appropriate", "/əˈproʊpriət/", "合适的；恰当的", "Choose an appropriate word.", "proper 的近义词，更正式。"],
  ["approve", "/əˈpruːv/", "赞成；批准", "The teacher approved my plan.", "approval 是批准、赞同。"],
  ["argue", "/ˈɑːrɡjuː/", "争论；论证", "They argued about the result.", "argument 是争论或论点。"],
  ["arrange", "/əˈreɪndʒ/", "安排；整理", "Arrange your review before dinner.", "arrangement 是安排。"],
  ["aspect", "/ˈæspekt/", "方面；外观", "Vocabulary is one aspect of English.", "常考搭配：in every aspect。"],
  ["assess", "/əˈses/", "评估；评价", "Assess your progress each week.", "assessment 是评估。"],
  ["assign", "/əˈsaɪn/", "分配；布置", "The teacher assigned ten exercises.", "assignment 是作业。"],
  ["assist", "/əˈsɪst/", "帮助；协助", "This app assists your review.", "assistant 是助手。"],
  ["assume", "/əˈsuːm/", "假定；认为", "Do not assume every word is easy.", "assumption 是假设。"],
  ["attach", "/əˈtætʃ/", "贴上；附上；重视", "Attach the file to your message.", "attachment 是附件。"],
  ["attempt", "/əˈtempt/", "尝试；企图", "Make an attempt to speak English.", "attempt to do 尝试做。"],
  ["available", "/əˈveɪləbl/", "可获得的；有空的", "The book is available online.", "常考：be available to sb.。"],
  ["average", "/ˈævərɪdʒ/", "平均的；普通的", "The average score improved.", "average 可作名词、形容词、动词。"],
  ["avoid", "/əˈvɔɪd/", "避免", "Avoid reviewing only before exams.", "avoid doing sth. 避免做某事。"],
  ["benefit", "/ˈbenɪfɪt/", "益处；受益", "Daily reading benefits your vocabulary.", "benefit from 从中受益。"],
  ["brief", "/briːf/", "简短的；摘要", "Give a brief answer.", "briefly 简要地。"],
  ["capacity", "/kəˈpæsəti/", "能力；容量", "Memory capacity grows with practice.", "cap 像帽子装东西，capacity 容量。"],
  ["challenge", "/ˈtʃælɪndʒ/", "挑战", "The exam is a challenge.", "challenge yourself 挑战自己。"],
  ["circumstance", "/ˈsɜːrkəmstæns/", "情况；环境", "Act according to the circumstance.", "under no circumstances 绝不。"],
  ["combine", "/kəmˈbaɪn/", "结合；联合", "Combine reading with listening.", "combination 是结合。"],
  ["comfort", "/ˈkʌmfərt/", "安慰；舒适", "A routine gives comfort.", "comfortable 舒适的。"],
  ["commit", "/kəˈmɪt/", "承诺；犯错；投入", "Commit yourself to daily study.", "commit to 坚持投入。"],
  ["communicate", "/kəˈmjuːnɪkeɪt/", "交流；传达", "Words help us communicate.", "communication 是交流。"],
  ["compare", "/kəmˈper/", "比较", "Compare similar words carefully.", "compare with/to 都常见。"],
  ["compete", "/kəmˈpiːt/", "竞争", "Students compete for better scores.", "competition 是竞争。"],
  ["complex", "/ˈkɑːmpleks/", "复杂的", "This sentence is complex.", "complex 不等于 difficult，但常相关。"],
  ["concentrate", "/ˈkɑːnsntreɪt/", "集中注意力", "Concentrate on one task.", "concentrate on 固定搭配。"],
  ["concept", "/ˈkɑːnsept/", "概念；观念", "Understand the concept first.", "conception 可表示观念。"],
  ["concern", "/kənˈsɜːrn/", "关心；担忧；涉及", "The problem concerns every student.", "be concerned about 关心、担心。"],
  ["conduct", "/kənˈdʌkt/", "实施；引导；行为", "They conducted a survey.", "作名词时重音常在前。"],
  ["confirm", "/kənˈfɜːrm/", "确认；证实", "Confirm the answer before moving on.", "confirmation 是确认。"],
  ["conflict", "/ˈkɑːnflɪkt/", "冲突；矛盾", "There is a conflict between them.", "和 fight 不同，更偏矛盾。"],
  ["consequence", "/ˈkɑːnsəkwens/", "结果；后果", "Every choice has a consequence.", "as a consequence 因此。"],
  ["consider", "/kənˈsɪdər/", "考虑；认为", "Consider your weak points.", "consider doing sth. 考虑做某事。"],
  ["consistent", "/kənˈsɪstənt/", "一致的；持续的", "Consistent practice matters.", "consistently 持续地。"],
  ["consume", "/kənˈsuːm/", "消耗；消费", "Scrolling consumes your time.", "consumer 是消费者。"],
  ["contribute", "/kənˈtrɪbjuːt/", "贡献；促成", "Sleep contributes to memory.", "contribution 是贡献。"],
  ["convenient", "/kənˈviːniənt/", "方便的", "Mobile review is convenient.", "convenience 是方便。"],
  ["convince", "/kənˈvɪns/", "使相信；说服", "The evidence convinced me.", "convince sb. of sth. 使某人相信。"],
  ["create", "/kriˈeɪt/", "创造；创建", "Create a study habit.", "creative 有创造力的。"],
  ["crucial", "/ˈkruːʃl/", "关键的；至关重要的", "Review is crucial for vocabulary.", "critical 的近义词。"],
  ["decline", "/dɪˈklaɪn/", "下降；拒绝", "His interest began to decline.", "也可表示礼貌拒绝。"],
  ["define", "/dɪˈfaɪn/", "定义；明确", "Define your daily goal.", "definition 是定义。"],
  ["demonstrate", "/ˈdemənstreɪt/", "证明；展示", "The chart demonstrates progress.", "demo 像展示。"],
  ["depend", "/dɪˈpend/", "依靠；取决于", "Success depends on practice.", "depend on 固定搭配。"],
  ["deserve", "/dɪˈzɜːrv/", "值得；应得", "Your effort deserves respect.", "deserve to do 值得做。"],
  ["determine", "/dɪˈtɜːrmɪn/", "决定；确定", "Your habits determine your result.", "determined 坚定的。"],
  ["develop", "/dɪˈveləp/", "发展；培养", "Develop a review habit.", "development 是发展。"],
  ["efficient", "/ɪˈfɪʃnt/", "高效的", "An efficient method saves time.", "efficiency 是效率。"],
  ["emphasize", "/ˈemfəsaɪz/", "强调", "The teacher emphasized review.", "emphasis 是强调。"],
  ["enable", "/ɪˈneɪbl/", "使能够", "Good tools enable better learning.", "enable sb. to do 使某人能做。"],
  ["encounter", "/ɪnˈkaʊntər/", "遇到；遭遇", "You will encounter new words daily.", "count 不发核心意思，记整体。"],
  ["enhance", "/ɪnˈhæns/", "提高；增强", "Reading enhances vocabulary.", "enhancement 是提升。"],
  ["ensure", "/ɪnˈʃʊr/", "确保", "Review ensures long-term memory.", "ensure that 确保。"],
  ["essential", "/ɪˈsenʃl/", "必要的；本质的", "Vocabulary is essential.", "essence 是本质。"],
  ["evaluate", "/ɪˈvæljueɪt/", "评价；评估", "Evaluate your answer.", "value 在里面，评估价值。"],
  ["evidence", "/ˈevɪdəns/", "证据", "There is clear evidence.", "evident 是明显的。"],
  ["expand", "/ɪkˈspænd/", "扩大；扩展", "Expand your vocabulary step by step.", "ex- 向外，pand 展开。"],
  ["expose", "/ɪkˈspoʊz/", "暴露；接触", "Expose yourself to English every day.", "exposure 是接触、暴露。"],
  ["feature", "/ˈfiːtʃər/", "特点；功能", "This feature helps review.", "常见于产品、文章。"],
  ["frequent", "/ˈfriːkwənt/", "频繁的", "Frequent review is useful.", "frequency 是频率。"],
  ["generate", "/ˈdʒenəreɪt/", "产生；生成", "Practice generates confidence.", "generation 是一代、生成。"],
  ["identify", "/aɪˈdentɪfaɪ/", "识别；确认", "Identify your weak words.", "identity 是身份。"],
  ["ignore", "/ɪɡˈnɔːr/", "忽视", "Do not ignore small mistakes.", "ignorance 是无知。"],
  ["improve", "/ɪmˈpruːv/", "改善；提高", "Review improves memory.", "improvement 是提高。"],
  ["indicate", "/ˈɪndɪkeɪt/", "表明；指出", "The result indicates progress.", "indicator 是指标。"],
  ["individual", "/ˌɪndɪˈvɪdʒuəl/", "个人；单独的", "Each individual has a method.", "divide 分开，individual 个体。"],
  ["influence", "/ˈɪnfluəns/", "影响", "Habits influence results.", "可作名词和动词。"],
  ["maintain", "/meɪnˈteɪn/", "维持；保养", "Maintain your study streak.", "maintenance 是维护。"],
  ["motivate", "/ˈmoʊtɪveɪt/", "激励", "Goals motivate action.", "motivation 是动力。"],
  ["obtain", "/əbˈteɪn/", "获得", "Obtain information from reliable sources.", "比 get 更正式。"],
  ["participate", "/pɑːrˈtɪsɪpeɪt/", "参加；参与", "Participate in class actively.", "participate in 固定搭配。"],
  ["potential", "/pəˈtenʃl/", "潜力；潜在的", "You have great potential.", "potentially 潜在地。"],
  ["priority", "/praɪˈɔːrəti/", "优先事项", "Make review a priority.", "prior 表示更早、更优先。"],
  ["purchase", "/ˈpɜːrtʃəs/", "购买", "She purchased a dictionary.", "比 buy 更正式。"],
  ["reduce", "/rɪˈduːs/", "减少；降低", "Review reduces forgetting.", "reduction 是减少。"],
  ["reflect", "/rɪˈflekt/", "反映；思考", "Reflect on your mistakes.", "reflection 是反思、倒影。"],
  ["reliable", "/rɪˈlaɪəbl/", "可靠的", "Use reliable materials.", "rely on 依靠。"],
  ["require", "/rɪˈkwaɪər/", "需要；要求", "Success requires patience.", "requirement 是要求。"],
  ["resource", "/ˈriːsɔːrs/", "资源", "Time is a valuable resource.", "learning resources 学习资源。"],
  ["respond", "/rɪˈspɑːnd/", "回答；回应", "Respond quickly in practice.", "response 是回应。"],
  ["significant", "/sɪɡˈnɪfɪkənt/", "重要的；显著的", "There was significant progress.", "significance 是意义。"],
  ["strategy", "/ˈstrætədʒi/", "策略", "A review strategy helps memory.", "strategic 战略性的。"],
  ["sufficient", "/səˈfɪʃnt/", "足够的", "Sufficient review prevents forgetting.", "enough 的正式表达。"],
  ["temporary", "/ˈtempəreri/", "暂时的", "Forgetting is temporary if you review.", "temp 和 time 有关。"],
  ["transfer", "/trænsˈfɜːr/", "转移；调动", "Transfer words into active use.", "trans- 跨过去。"],
  ["unique", "/juˈniːk/", "独特的；唯一的", "Everyone has a unique memory path.", "uni- 一个。"]
].map(([word, phonetic, meaning, example, hint], index) => ({
  id: `builtin-${index + 1}`,
  word,
  phonetic,
  meaning,
  example,
  hint,
  source: "专升本高频核心"
}));
